### ISSUE TITLE
Not working on 4.4. chip

### ISSUE THREAD

**Issue by clarity99** [fordsfords/wlan_pwr#1]
I installed this on 4.4. headless and it does not seem to be working. after reboot power config is on. if I run the file manually, power config gets turned off.

**Comment by fordsfords** [comment]
Hmm ... it works for me.  Did you perform these commands, as shown in the quickstart doc?

<pre>
sudo wget -O/etc/network/if-up.d/wlan_pwr http://fordsfords.github.io/wlan_pwr/wlan_pwr
sudo chmod +x /etc/network/if-up.d/wlan_pwr
</pre>

**Comment by fordsfords** [comment]
Show the output of:

<pre>
ls -l /etc/network/if-up.d
</pre>

**Comment by snawolf** [comment]
It didn't work for me either, on the gui 4.4 -- I tried it twice

chip@chip:~$ ls -l /etc/network/if-up.d
total 32
-rwxr-xr-x 1 root root  923 Apr 14  2015 avahi-autoipd
-rwxr-xr-x 1 root root  484 Apr 14  2015 avahi-daemon
-rwxr-xr-x 1 root root 4958 Apr  6  2015 mountnfs
-rwxr-xr-x 1 root root 1089 Sep 16  2008 ntpdate
-rwxr-xr-x 1 root root  945 Apr 15  2016 openssh-server
-rwxr-xr-x 1 root root 1483 Jan  7  2013 upstart
-rwxr-xr-x 1 root root  427 Sep 27 17:55 wlan_pwr
lrwxrwxrwx 1 root root   32 Aug  2 06:20 wpasupplicant -> ../../wpa_supplicant/ifupdown.sh

**Comment by ExplodingLemur** [comment]
This appears to be a problem with iwconfig on the CHIP 4.4 image.
```
chip@chip:/$ sudo iwconfig wlan0 power off
Error for wireless request "Set Power Management" (8B2C) :
    SET failed on device wlan0 ; Operation not permitted.
```

Using the iw tool instead works:
sudo iw dev wlan0 set power_save off

**Comment by stormbard** [comment]
I'm running into this issue as well with  4.4.13-ntc-mlc.  I'm also seeingthat iwconfig is being replaced by iw according to https://wireless.wiki.kernel.org/en/users/documentation/iw/replace-iwconfig. In fact when you run iwconfig just to get the information it seems to report wrong with respect to the power settings.

**Comment by fordsfords** [comment]
Ok, I updated wlan_pwr to use "iw".

Thanks @ExplodingLemur and @stormbard for doing the research for me!  :-)
