### ISSUE TITLE
wlan_pwr needed changes for Debian 8.11 to work properly

### ISSUE THREAD

**Issue by kenmartin-unix** [fordsfords/wlan_pwr#5]
Executing  on reboot wlan_pwr the variable ADDRFAM is never set to "inet" so the script exits. Also, the variable IFNAME is never set to wlan0 or wlan1 it is always set to "-all". So power save is never turned off. See modified script below. I can be contacted at ken.at.github@gmail.com. Results can be seen after install and re-boot by  cat /var/log/syslog | grep WLAN

#! /bin/sh
# wlan_pwr -- version: "25-Jun-2020"
# Improve CHIP's wireless performance by turning off power management.
set -e
echo "WLAN_PWR: IFACE $IFACE, MODE $MODE, ADDRFAM "
# Don't bother for loopback
if [ "$IFACE" = lo ]; then
	exit 0
fi
# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi
# Hopefully wireless-tools is installed
if [ ! -x /sbin/iw ]; then
	exit 0
fi
echo "WLAN_PWR: Setting power save to off"
/sbin/iw dev wlan0 set power_save off
/sbin/iw dev wlan1 set power_save off
exit 0

**Comment by fordsfords** [comment]
Hi Ken.

Unfortunately, it's a bit hard to see what your changes were. Could you submit a pull request? That will make my job easier.

Also, I don't have a running C.H.I.P. at the moment. So I can't test  your changes against the standard OS (is there a standard any more?). So give your changes some thought as to whether they are backwards compatible with older OS. If not, then a fork might be the better approach. If you fork it for Debian 8.11, I can include a link to your repo.

Thanks
Steve

**Comment by kenmartin-unix** [comment]
Attached is the original modified script. I don't get this pull stuff. I'm too old.
I have burned all my CHIP's to Debian 8.11. Can't burn backwards.

#! /bin/sh
# wlan_pwr -- version: "11-Apr-2020"
# Tested on Debian 
# Improve CHIP's wireless performance by turning off power management.

set -e

# Log settings new
# This way you can 'cat /var/log/syslog | grep wlan_pwr'  to see activity.
echo "wlan_pwr: IFACE $IFACE, MODE $MODE, ADDRFAM $ADDRFAM"

# Don't bother for loopback
if [ "$IFACE" = lo ]; then
	exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi

# old off inet is never passed
# Only do it once (skip for inet6).
# if [ "$ADDRFAM" != inet ]; then
#	exit 0
# fi

# Hopefully wireless-tools is installed
if [ ! -x /sbin/iw ]; then
	exit 0
fi

# New
# The IFACE argument is not passed
# /sbin/iw dev $IFACE set power_save off
# Insert run through available wlans
echo "wlan_pwr: Setting power saving to off"
# Get list of available wlans
for wifi in `ip a | grep wlan | cut -f2 -d ' ' | sed "s/://"`
        do
       # Log work done for each
        echo "wlan_pwr: Power save to off for $wifi"
        /sbin/iw dev $wifi set power_save off
        echo -n "wlan_pwr: $wifi is set to "
        /sbin/iw dev $wifi get power_save
        done

exit 0

**Comment by guysoft** [comment]
Can you put that comment in and before ```
Because its impossible to read it because it gets converted to markdown

**Comment by guysoft** [comment]
Ok, not impossible but tedious.

Here is the script with the escape chars:
```
#!/bin/sh
# wlan_pwr -- version: "11-Feb-2017"
# Improve CHIP's wireless performance by turning off power management.

set -e

# Log settings new
# This way you can 'cat /var/log/syslog | grep wlan_pwr' to see activity
echo "wlan_pwr: IFACE $IFACE, MODE $MODE, ADDRFAM $ADDRFAM"

# Don't bother for loopback
if [ "$IFACE" = lo ]; then
        exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
        exit 0
fi

# old off inet is never passed
# Only do it once (skip for inet6).
if [ "$ADDRFAM" != inet ]; then
        exit 0
fi

# Hopefully wireless-tools is installed
if [ ! -x /sbin/iw ]; then
        exit 0
fi

# The IFACE argument is not passed
# Insert run through available wlans
echo "wlan_pwr: Setting power saving to off"

# Get list of available wlans
for wifi in `ip a | grep wlan | cut -f2 -d ' ' | sed "s/://"`
do
  # Log work done for each
  echo "wlan_pwr: Power save to off for $wifi"
  /sbin/iw dev $wifi set power_save off
  echo -n "wlan_pwr: $wifi is set to "
  /sbin/iw dev $wifi get power_save
done

exit 0
```

I am on RaspberryPi OS buster and it does not work, ``wlan0`` says ``Power Management:on``.

This tool does though give a way to debug why the script does not work.
running ``cat /var/log/syslog | grep wlan_pwr`` gives:

```
Feb 10 09:06:19 octopi ifup[274]: wlan_pwr: IFACE lo, MODE start, ADDRFAM inet
Feb 10 09:06:19 octopi ifup[274]: wlan_pwr: IFACE --all, MODE start, ADDRFAM meta
```

So it seems IFACE is ``--all`` and not wlan.

**Comment by fordsfords** [comment]
Hi guys. I'm going to close this issue since they are related to Debian 8.11, and my C.H.I.P. is stuck on its original OS. (And I haven't even turned it on in over 3 years.) Since I don't have Debian to experiment on, I can't really help you debug this. Sorry. I suggest forking this project and changing it for Debian. If you get it working reliably, I'll include a link to your forked repo.

**Comment by guysoft** [comment]
Ah cool, didn't realise it was for the C.H.I.P. I still have one laying around here, not sure what to do with it
